local f = CreateFrame("Frame")
f:RegisterEvent("ADDON_LOADED")
f:SetScript("OnEvent", function(self, event, name)
	if name == "Blizzard_Collections" then
		ApplyDropDown(HeirloomsJournal.ClassDropdown)
		ApplyDropDown(WardrobeCollectionFrame.ItemsCollectionFrame.WeaponDropdown)
		ApplyFilterDropDown(MountJournal.FilterDropdown)
		ApplyFilterDropDown(PetJournal.FilterDropdown)
		ApplyFilterDropDown(ToyBox.FilterDropdown)
		ApplyFilterDropDown(HeirloomsJournal.FilterDropdown)
		ApplyFilterDropDown(WardrobeCollectionFrame.FilterButton)

		PetJournal:HookScript("OnShow", function(self)
			self:GetParent().portrait:SetTexCoord(0, 1, 0, 1)
		end)
		ToyBox:HookScript("OnShow", function(self)
			SetPortraitToTexture(self:GetParent().portrait, "Interface\\Icons\\Trade_Archaeology_ChestofTinyGlassAnimals")
			self:GetParent().portrait:SetTexCoord(0, 1, 0, 1)
		end)
		HeirloomsJournal:HookScript("OnShow", function(self)
			self:GetParent().portrait:SetTexCoord(0, 1, 0, 1)
		end)
		WardrobeCollectionFrame:HookScript("OnShow", function(self)
			self:GetParent().portrait:SetTexCoord(0, 1, 0, 1)
		end)
	end
end)