local f = CreateFrame("Frame")
f:RegisterEvent("ADDON_LOADED")
f:SetScript("OnEvent", function(self, event, name)
	if name == "Blizzard_PVPUI" then
		ApplyDropDown(HonorFrameTypeDropdown)
		HonorFrameTypeDropdown:SetWidth(175)
		HonorFrameTypeDropdown:SetPoint("BOTTOMRIGHT", HonorFrame.Inset, "TOPRIGHT", -11, 5)
		HonorFrameTypeDropdown.Text:SetJustifyH("RIGHT")
		HonorFrameTypeDropdown.Text:SetPoint("TOPLEFT", 9, -7)
		ApplyDropDown(TrainingGroundsFrameTypeDropdown)
		TrainingGroundsFrameTypeDropdown:SetWidth(175)
		TrainingGroundsFrameTypeDropdown:SetPoint("BOTTOMRIGHT", TrainingGroundsFrame.Inset, "TOPRIGHT", -11, 5)
		TrainingGroundsFrameTypeDropdown.Text:SetJustifyH("RIGHT")
		TrainingGroundsFrameTypeDropdown.Text:SetPoint("TOPLEFT", 9, -7)
	end
end)