if not _G.WorldMapFrame then return end

ApplyDropDown(WorldMapZoneMinimapDropdown)
ApplyDropDown(WorldMapContinentDropdown)
ApplyDropDown(WorldMapZoneDropdown)
ApplyDropDown(WorldMapFrame.WorldMapLevelDropDown)
ApplyDropDown(WorldMapFrame.WorldMapOptionsDropDown)